### ISSUE TITLE
Web version doesn't set "Opts" comment

### ISSUE THREAD

**Issue by neuschaefer** [lvgl/lv_font_conv#100]
## Background

Due to the way the code currently works, the "Opts:" line in the generated C file is only set when using the command-line version, not the web version.

[lv_font.c:66+](https://github.com/lvgl/lv_font_conv/blob/master/lib/writers/lvgl/lv_font.js#L66):
```
 * Size: ${this.src.size} px
 * Bpp: ${this.opts.bpp}
 * Opts: ${process.argv.slice(2).join(' ')}
```

This leads to the meta-information such as font name, size, and character ranges getting lost when the web version is used.

## Request

To preserve these metadata, it would be nice to fake a command line in `web/index.js` and pass it to `convert`.

**Comment by kisvegabor** [comment]
It would be really great! I don't know the font converter well enough to add it my self. Do you have time and interested to work on it?

**Comment by neuschaefer** [comment]
I've gained some familiarity with the code over the past week, I'd like to implement this feature in coming 1-2 weeks

**Comment by kisvegabor** [comment]
It's amazing!
