### ISSUE TITLE
Link to live version

### ISSUE THREAD

**Issue by neuschaefer** [lvgl/lv_font_conv#101]
It would be nice to have a link from the GitHub repo to the live version running at https://lvgl.io/tools/fontconverter, so that users who find this repo can know at a glance that they don't have to set up node.js in order to use it.

**Comment by kisvegabor** [comment]
Good idea! Added here
![image](https://github.com/lvgl/lv_font_conv/assets/7599318/06702f5d-c274-4cab-bf02-4e0722111a18)
