### ISSUE TITLE
web: "Opts" includes empty "--range" parameter

### ISSUE THREAD

**Issue by neuschaefer** [lvgl/lv_font_conv#107]
I just noticed a bug in my code (https://github.com/lvgl/lv_font_conv/pull/106): The `--range` parameter is emitted even when there are no ranges.

```
Opts: ...  --range  --format lvgl -o font.c
```

**Comment by kisvegabor** [comment]
Can you send a PR to fix it?

**Comment by neuschaefer** [comment]
I'll give it a try over the weekend

**Comment by sunzigang** [comment]
I had the same problem, this commit might fix the bug .   https://github.com/lvgl/lv_font_conv/pull/108

**Comment by neuschaefer** [comment]
> I had the same problem, this commit might fix the bug . #108

Your PR looks good, but it doesn't seem to fix this particular issue: The converter still emits an empty `--ranges` option
