### ISSUE TITLE
Update the npm repo to v1.5.3

### ISSUE THREAD

**Issue by Linjieqiang** [lvgl/lv_font_conv#113]
![image](https://github.com/lvgl/lv_font_conv/assets/10217966/e1adcf38-a1db-4a66-a16c-fe4afa0d1409)
![image](https://github.com/lvgl/lv_font_conv/assets/10217966/c2a19950-849d-46dc-a868-b2e1373a4e26)

Need to update to support the lvgl9 font

**Comment by Oshekho** [comment]
Could you please make a new tag? The latest tag is 1.5.2 and it goes back to 2021. This tag is not compatible with v9.

**Comment by kisvegabor** [comment]
I can tag it to v1.6? Do you agree with that?
