### ISSUE TITLE
Bitmap font (pcf and/or bdf format)

### ISSUE THREAD

**Issue by razor5k** [lvgl/lv_font_conv#114]
Hi, 
I've a display which has a resolution of 256x64 Pixel (SSD1322 controller) and I need also small font sizes (8px and so on).
But every rendered font don't look very pretty. Is it possible to edit a font after rendering (with a font editor tool from lvgl or something) or can I use bitmap fonts such as pcf or bdf format?
Does lv_font_conv handle bitmap information embedded in ttf or otf etc? If I disable autohinting, the font seems to look better but I thought hinting should make the font better look.

**Comment by kisvegabor** [comment]
Unfortunately there is no easy way to edit the generated fonts.
 
For monochrome displays I think the best you can do is selecting a pixel font. The [Terminus](https://sourceforge.net/projects/terminus-font/) font might be a good first candidate. 

Alternatively you can try [Image font](https://docs.lvgl.io/master/others/imgfont.html).

**Comment by razor5k** [comment]
Thx. I tested Terminus and it looks very pretty. It's a mono space font and it looks very 'sharp'. I also found a way to "convert" a bdf to a ttf. Binary information of the bdf files will be embedded to a single ttf file by using 'mkttf'. It uses fontforge, imagemagick and potrace. Now I'm able to use every bdf font. It would be nice if lvgl_font_converter could use the bdf format as well. Because the pixel information is directly available, no complicated rendering would be necessary. But mkttf works for me as well :)

**Comment by kisvegabor** [comment]
The font converter uses FreeType, so we can use the font types supported by FreeType. 

Would you be interested in documenting the process of bdf to ttf conversation? If so I think a section after [this](https://docs.lvgl.io/master/overview/font.html#load-a-font-from-a-memory-buffer-at-run-time) would be quite useful for others. (You need to edit [this file](https://github.com/lvgl/lvgl/blob/master/docs/overview/font.rst) to update the docs)

**Comment by razor5k** [comment]
Yes, I will document the use of the BDF files in the next few days.

**Comment by kisvegabor** [comment]
Great, thank you!

**Comment by pnb990** [comment]
> Yes, I will document the use of the BDF files in the next few days.

I found document and it work well ! thanks
https://docs.lvgl.io/master/details/main-components/font.html#convert-bdf-to-ttf

**Comment by kisvegabor** [comment]
Great, closing this issue then 🚀
