### ISSUE TITLE
Non-Clickable Link in the "About" Section

### ISSUE THREAD

**Issue by hayschan** [lvgl/lv_font_conv#129]
The link provided in the "About" section of this repository (`https://lvgl.io/tools/fontconverter`) is not clickable. This could be due to a misconfiguration in the GitHub "About" section settings.

![image](https://github.com/user-attachments/assets/e7116656-d7f1-490b-aec4-fdb57416c847)

**Steps to Reproduce:**  

1. Visit the repository's main page.  
2. Check the "About" section on the right-hand side.  
3. Attempt to click the provided link.

**Expected Behavior:**  

The link in the "About" section should be clickable, directing users to the specified page.

**Actual Behavior:**  

The link appears as plain text and is not clickable.

**Comment by kisvegabor** [comment]
Fixed, thank you!
