### ISSUE TITLE
Check for very large fonts

### ISSUE THREAD

**Issue by kisvegabor** [lvgl/lv_font_conv#47]
Hi,

Right now there is an [LV_FONT_FMT_TXT_LARGE](https://github.com/lvgl/lvgl/blob/565643e88387a305bd02ccf612a2ee4c969cabc9/src/lv_font/lv_font_fmt_txt.h#L30-L46) switch in LVGL to choose between a more compact description of glyphs or a larger one for large fonts. 

It was already reported several times that LVGL is not working with large fonts but only `LV_FONT_FMT_TXT_LARGE` needed to be enabled.

I wonder if we could do a check in the generated fonts like:
```c
#if (LV_FONT_FMT_TXT_LARGE == 0)
# error "Too large font or glyphs in <font_name>. Enable LV_FONT_FMT_TXT_LARGE in lv_conf.h")
#endif
```

These line neds to added if
```
bitmap_array_size >= 1024 * 1024
any adv_w > 4096
any abs(ofs_x) or abs(ofs_y) > 127
any box_w or box_h > 255 
```

Let me know what you think.

**Comment by puzrin** [comment]
If this is preferable solution for you, i see no principal problems. `--format lvgl` is based on your demands, and until it not break spec i don't care what happens inside.

- What about switch to binary format and drop text one with all it's hacks? In v9, when tests arranged. Or you still think text format has some advantages?

**Comment by kisvegabor** [comment]
> If this is preferable solution for you, i see no principal problems. --format lvgl is based on your demands, and until it not break spec i don't care what happens inside.

Great!
Is it something you can add quickly or shall I play with it?

> What about switch to binary format and drop text one with all it's hacks? In v9, when tests arranged. Or you still think text format has some advantages?

We need to estimate its impact on performance. Right now the details are not in my head so can't say anything about it. 
Anyway, we can put it to the roadmap to discuss it.

**Comment by puzrin** [comment]
> Is it something you can add quickly or shall I play with it?

If it's not urgent, i can add in 1-2 weeks. May be sooner, but not sure.

> We need to estimate its impact on performance. Right now the details are not in my head so can't say anything about it.
Anyway, we can put it to the roadmap to discuss it.

If now performance is the only concern for you, please add to roadmap. I think, this will not be a big deal. ~ to v9+ (without tests this will be fragile).

**Comment by kisvegabor** [comment]
> If it's not urgent, i can add in 1-2 weeks. May be sooner, but not sure.

It's not that urgent, so 1-2 weeks is perfect. Thank you in advance.

> If now performance is the only concern for you, please add to roadmap. I think, this will not be a big deal. ~ to v9+ (without tests this will be fragile).

Added: https://github.com/lvgl/lvgl/blob/master/docs/ROADMAP.md

**Comment by puzrin** [comment]
https://github.com/lvgl/lv_font_conv/commit/c23c5b95f7b173582722953849c95f8dc071c660

Could you check if it works as you need? (dev branch)

**Comment by puzrin** [comment]
@kisvegabor thanks for review. Please check fixes (force-pushed)

**Comment by kisvegabor** [comment]
Thanks! I got this error:
```shell
> lv_font_conv --font ../Roboto-Regular.woff --range 0x20-0x100 --size 100 --bpp 4 --format lvgl --output a.c
TypeError: Cannot read property 'glyph' of undefined
    at LvFont.large_format_guard (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/lv_font_conv/lib/writers/lvgl/lv_font.js:37:15)
    at LvFont.toLVGL (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/lv_font_conv/lib/writers/lvgl/lv_font.js:85:8)
    at Object.write_images [as lvgl] (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/lv_font_conv/lib/writers/lvgl/index.js:15:25)
    at convert (/home/kisvegabor/.nvm/versions/node/v11.2.0/lib/node_modules/lv_font_conv/lib/convert.js:25:35)

```

**Comment by puzrin** [comment]
Ups... sorry. Try bugfix. A least, it now injects condition with `--size 400`

**Comment by kisvegabor** [comment]
It works well, thank you!

**Comment by puzrin** [comment]
Published

**Comment by kisvegabor** [comment]
Thank you very much!
I've also updated the online converter.
