### ISSUE TITLE
lvgl include directive

### ISSUE THREAD

**Issue by alsaleem00** [lvgl/lv_font_conv#48]
The exported font.c file refers to lvgl.h as
`#include "lvgl/lvgl.h"`
Since user will insert this file under the lvgl/src/lv_fon, the correct way to include is:
`#include "../lvgl.h"`

I had to do this manually otherwise it wont compile.

**Comment by embeddedt** [comment]
Actually, it's not necessary to put the font in `lvgl/src/lv_font`. If your include path is set up correctly (so that `lvgl/lvgl.h` is a valid path), everything should work out of the box.
