### ISSUE TITLE
Reduce npm bundle size

### ISSUE THREAD

**Issue by puzrin** [lvgl/lv_font_conv#49]
In 1.2.0, after all deps bundled into npm package, `npx lv_font_conv -h` runs MUCH faster.

- 3s for first run
- 1.8s for next immediate run

Probably, this an be better, if reduce bundle size/content. Quick investigation (via `npm pack`):

- 1600К - current
- 973К - remove openype.js unused files
- 651К - if rewrite to not use lodash
- 590К - drop pngjs garbage

**Comment by puzrin** [comment]
Done.

In 1.3.0 bootstrap time reduced to 1.5s (bundle size 476K). Looks useable.

**Comment by puzrin** [comment]
@kisvegabor please switch to 1.3.0 and let me know if something wrong.

I did quick-check, bin & lvgl generated files seems not changed. But it's better to run more with real projects.

**Comment by kisvegabor** [comment]
I rebuilt and got this:
```
npm run build

> lv_font_conv@1.1.3 build /home/kisvegabor/projects/littlevgl/lv_font_conv/lv_font_conv
> parcel build ./web/index.html ./web/content.html --public-url ./

✨  Built in 840ms.

dist/web.4313d631.js.map    ⚠️  2.66 MB    154ms
dist/web.4313d631.js         944.28 KB    354ms
dist/index.html                7.17 KB    256ms
dist/content.html              6.42 KB     11ms
```

So it's still quite large for me. Am I doing something wrong?

**Comment by puzrin** [comment]
I cared about npm size only (for `npx` use). But web size should decrease to:

- `.map` - source map, not counted
- `.js` - gzip prior to compare.

In other words - everything ok. You can compare with 1.1.x, if interested.

**Comment by kisvegabor** [comment]
Alright than. The new version is added to  website.
