### ISSUE TITLE
Issue with missing subpixel3 element in index.js in online font converter

### ISSUE THREAD

**Issue by tonystuart** [lvgl/lv_font_conv#50]
I've been using the online font converter the last few days. This morning, using the same workflow as before, I cannot get it to convert a font. When I press the Convert button nothing happens. I've tried Chrome 85.0.4183.121 and Firefox 81.0.

Chrome developer tools reports an exception on line 110 of index.js:

lcd_v: document.getElementById('subpixel3').checked,

It appears that the element subpixel3 does not exist.

Not sure if it's relevant, but there is also a report of a problem with a missing font:

https://lvgl.io/tools/assets/fonts/Montserrat-Regular.ttf

It's a great utility, and has been very easy to use, so perhaps it's something I'm doing wrong.

Many thanks!

**Comment by puzrin** [comment]
Does cli tool work?

**Comment by kisvegabor** [comment]
Sorry, it was me. Just reverted the changes.
