### ISSUE TITLE
no such file or directory? Can't open the font file.

### ISSUE THREAD

**Issue by Pupil2013** [lvgl/lv_font_conv#51]
I place the font file  WeiRuanYaHei-1.ttf at the same folder with lv_font_conv.js  and run `lv_font_conv --bpp 4 --size 16 --format bin --font WeiRuanYaHei-1.ttf -r 0x4e00` then lv_font_conv.js: error: Cannot read file "WeiRuanYaHei-1.ttf": ENOENT: no such file or directory, open 'WeiRuanYaHei-1.ttf'
Am I using it the wrong way?
 I'm runing it on windows

**Comment by puzrin** [comment]
Font path is calculated from current dir, not from package dir. Try use full absolute path for sure.
