### ISSUE TITLE
Fix lvgl.h include

### ISSUE THREAD

**Issue by bku-sue** [lvgl/lv_font_conv#52]
Fix the file headers to match convention:
```
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include <lvgl.h>
#else
#include <lvgl/lvgl.h>
#endif
```

**Comment by puzrin** [comment]
https://github.com/lvgl/lv_font_conv/blob/master/lib/writers/lvgl/lv_font.js#L63

`--lv-include` allows to set any value you need dirctly.

@kisvegabor does this need update and how compatible is that (if yes)?

**Comment by bku-sue** [comment]
How can this be used in the online converter tool though? Meaning https://lvgl.io/tools/fontconverter

**Comment by puzrin** [comment]
No ideas. I don't know online wrapper state and would not recommend it. Probably, such question would be better on lvgl forum.

**Comment by kisvegabor** [comment]
I like the idea, it clearly more flexible than the current `#include <lvgl/lvgl.h>` way.

For the sake of simplicity, the online converter doesn't support every option.

**Comment by puzrin** [comment]
@kisvegabor can i use sample from first post as is or it needs some tweaks?

**Comment by kisvegabor** [comment]
Use this please. (only `<>` is changes to `""`)
```c
#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif
```

**Comment by puzrin** [comment]
Please check maser branch. If everything fine, i will publish.

**Comment by kisvegabor** [comment]
Looks good!
