### ISSUE TITLE
Unicode notation "U+"  should be  at least four digits like U+00B0 not U+B0

### ISSUE THREAD

**Issue by ponty** [lvgl/lv_font_conv#54]
https://en.wikipedia.org/wiki/Unicode
"prepended with leading zeros as necessary to result in a minimum of four digits"

This is the C code now:
```c
/* U+B0 "°" */
```

**Comment by embeddedt** [comment]
https://github.com/lvgl/lv_font_conv/blob/bd59adf5ddb1fb4645cafd921302a874f45bbd4b/lib/writers/lvgl/lv_table_glyf.js#L59-L62

Looks like `code_hex` needs to be padded with zeros.
