### ISSUE TITLE
Error when I run the command

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [lvgl/lv_font_conv#55]
Run respectively:
![Snipaste_2021-02-02_11-41-13](https://user-images.githubusercontent.com/57666259/106549603-46856800-654c-11eb-92bd-4d8f22f1e6b8.png)

**Comment by puzrin** [comment]
Check your nodejs version and upgrade to v14.+

**Comment by Tuzhiqiang1996** [comment]
Thank you!
