### ISSUE TITLE
The font size can be set to 50 to reach the maximum. Can you increase the value

### ISSUE THREAD

**Issue by Tuzhiqiang1996** [lvgl/lv_font_conv#56]
![Snipaste_2021-02-02_17-47-44](https://user-images.githubusercontent.com/57666259/106582519-08556c00-657f-11eb-91d0-deb779514f9d.png)

**Comment by puzrin** [comment]
Please provide details how to reproduce (font file, versions and so on)

**Comment by Tuzhiqiang1996** [comment]
[Roboto-Thin.zip](https://github.com/lvgl/lv_font_conv/files/5910273/Roboto-Thin.zip)
This is one of the font files.The above operation will report an error, I do not know what reason, thank you

**Comment by puzrin** [comment]
Rounding issue in kerning writer. Not size problem. As temporary kludge, try `--no-kerning`

Will fix asap.

**Comment by Tuzhiqiang1996** [comment]
I hope it didn't cause you any trouble. Thank you

**Comment by puzrin** [comment]
I can not reproduce

```
./lv_font_conv.js --font roboto-thin.ttf -r 0x20-0x7f --format lvgl --bpp 3 -o aaa.c --size 51
```

This works with your file.

Also did minor change https://github.com/lvgl/lv_font_conv/commit/ef5566006220f20cd745fec94e4107526c1f381b but code should work without it.

---

Need more details how to reproduce. Ideally - test repo with instructions.

**Comment by puzrin** [comment]
Close as outdated/nofeedback
