### ISSUE TITLE
lv_font_conv TypeError:  this.src.glyphs.map(...).flat is not a function

### ISSUE THREAD

**Issue by screep123** [lvgl/lv_font_conv#61]
I have following problem trying to play with lv_font_conv:

1. Download last revision from github:
git clone https://github.com/lvgl/lv_font_conv.git
2. Download libraries:
npm install
3. Run lv_font_conv with following command line:
node lv_font_conv --no-compress --no-prefilter --bpp 4 --size 12 --font Montserrat-Medium.ttf -r 0x20-0x7F,0xB0,0x2022 --format lvgl -o ./lv_font_montserrat_12.c --force-fast-kern-format

(with standard lvgl Montserrat-Medium.ttf font file

Get following error:

TypeError: this.src.glyphs.map(...).flat is not a function
    at new Font (/home/screep/lvgl/lv_font_conv/lib/font/font.js:38:99)
    at new LvFont (/home/screep/lvgl/lv_font_conv/lib/writers/lvgl/lv_font.js:16:5)
    at Object.write_images [as lvgl] (/home/screep/lvgl/lv_font_conv/lib/writers/lvgl/index.js:12:16)
    at convert (/home/screep/lvgl/lv_font_conv/lib/convert.js:25:35)

Could you please give me any ideas how to fix it?

PS:
node -v
v10.15.3

Thank you in advance

Looking forward for your reply

**Comment by embeddedt** [comment]
Your Node version is probably too old; try with v14.

**Comment by puzrin** [comment]
> TypeError: this.src.glyphs.map(...).flat is not a function

Very old node version, v10 will reach EOL in couple of months anyway https://nodejs.org/en/about/releases/.

Upgrade to 14. May be 12 can work too.

**Comment by screep123** [comment]
Thank you very much. It helped :)
