### ISSUE TITLE
Possible crash with node.js v16.13.1+

### ISSUE THREAD

**Issue by puzrin** [lvgl/lv_font_conv#70]
Ref: https://github.com/lvgl/lv_font_conv/issues/68

Font: [OPPOSans_OS_Medium.zip](https://github.com/lvgl/lv_font_conv/files/7844465/OPPOSans_OS_Medium.zip)

Seems node.js v16.13.1 introduced regression/restriction, causing convertor crash. Or wasm build outdated too much.

```sh
node -v
# => v16.13.1

git clone git@github.com:lvgl/lv_font_conv.git
cd lv_font_conv
npm i

./lv_font_conv.js --font OPPOSans_OS_Medium.ttf -r 0x20-0x2c63 --size 32 --format bin --bpp 4 --no-compress -o sans32.font
#RangeError: Maximum call stack size exceeded
#    at Math.max (<anonymous>)
#    at new Font (/home/vitaly/Загрузки/lv_font_conv/lib/font/font.js:38:27)
#    at Object.write_images [as bin] (/home/vitaly/Загрузки/lv_font_conv/lib/writers/bin.js:12:16)
#    at convert (/home/vitaly/Загрузки/lv_font_conv/lib/convert.js:25:35)
#    at async Object.module.exports.run (/home/vitaly/Загрузки/lv_font_conv/lib/cli.js:300:15)
```

**Temporary workaround**

Install node.js v16.13.0

**Comment by Pzhaowei** [comment]
> Ref: #68
> 
> Font: [OPPOSans_OS_Medium.zip](https://github.com/lvgl/lv_font_conv/files/7844465/OPPOSans_OS_Medium.zip)
> 
> Seems node.js v16.13.1 introduced regression/restriction, causing convertor crash. Or wasm build outdated too much.
> 
> ```shell
> node -v
> # => v16.13.1
> 
> git clone git@github.com:lvgl/lv_font_conv.git
> cd lv_font_conv
> npm i
> 
> ./lv_font_conv.js --font OPPOSans_OS_Medium.ttf -r 0x20-0x2c63 --size 32 --format bin --bpp 4 --no-compress -o sans32.font
> #RangeError: Maximum call stack size exceeded
> #    at Math.max (<anonymous>)
> #    at new Font (/home/vitaly/Загрузки/lv_font_conv/lib/font/font.js:38:27)
> #    at Object.write_images [as bin] (/home/vitaly/Загрузки/lv_font_conv/lib/writers/bin.js:12:16)
> #    at convert (/home/vitaly/Загрузки/lv_font_conv/lib/convert.js:25:35)
> #    at async Object.module.exports.run (/home/vitaly/Загрузки/lv_font_conv/lib/cli.js:300:15)
> ```
> 
> **Temporary workaround**
> 
> Install node.js v16.13.0

![222](https://user-images.githubusercontent.com/96897506/148903309-8b4dd68f-f030-4e76-bf76-b9ec6acd127a.png)
node.js v16.13.0 is the same problem.

**Comment by puzrin** [comment]
Thank you for info. v16.3.0 works in my case (Ubuntu).

Try latest v14 then, as workaround.

**Comment by Pzhaowei** [comment]
> Thank you for info. v16.3.0 works in my case (Ubuntu).
> 
> Try latest v14 then, as workaround.

![333](https://user-images.githubusercontent.com/96897506/148906574-9ce15e3e-d632-403d-802b-cb2311fa099d.png)
node.js v14 is the same problem.

**Comment by puzrin** [comment]
Thank you for help with localizing problem. I will continue investigation in nearest days. First, we will update wasm build with new compiler, and then will recheck again.

**Comment by Pzhaowei** [comment]
Excuse me, how is it going?

**Comment by puzrin** [comment]
Very busy at this moment. But i marked this bug with high priority, will take a look at the begining of next week.

**Comment by Pzhaowei** [comment]
Hello,how is it going?

**Comment by puzrin** [comment]
Still very busy, sorry. We rolled out very big software update on production site, and still fixing a lot of urgent issues.

**Comment by puzrin** [comment]
I've updated emcc, freetype and did fresh rebuild (see commits). Seems problem is specific to your concrete file only. Other fonts work without problems.

In any case - open/save font via FontForge before reporting problem.

Attached font after FF, seems to work.

[OPPOSans_OS_Medium_1.4.ttf.zip](https://github.com/lvgl/lv_font_conv/files/7917312/OPPOSans_OS_Medium_1.4.ttf.zip)
.
