### ISSUE TITLE
Difference in character padding between new font converter and old one

### ISSUE THREAD

**Issue by david-res** [lvgl/lv_font_conv#75]
I've recently been updating my project from v7.11 to v8.0 and I had converted my fonts again.
For v7 I used the older php based front converter on the lvgl.io website, and for v8 I used the current one which I believe is built on python.

[Here](https://www.youtube.com/watch?v=T4SWRsXsEUs) is a video of the same app running v8.0 to the left and v7.11 to the right.

Notice that on the right side no matter the physical length of the number, it is fixed to the decimal point.
Whereas with the exact same calibration code on the left side you can see the entire label moving just slightly left and right.

I tried the new converted font on v7.11 and can confirm the issue is not with lvgl library, but the font file.

Is there an option for you guys to convert a font on the old and new font converters and compare the output?

**Comment by puzrin** [comment]
Old font convertor did supported a lot of features (kerning and so on). So, any kind of claims "prev convertor was better" are invalid.

> Notice that on the right side no matter the physical length of the number, it is fixed to the decimal point.
Whereas with the exact same calibration code on the left side you can see the entire label moving just slightly left and right.

If you wish to stick decimal point position, here are your options:

- Use monospaced font
- Draw int/point/fract parts manually.

I understand, you may not like existing point drift on your video. But font is drawn exactly as designed. Problem is with wrong font use, not with convertor.

**Comment by puzrin** [comment]
> v7.11 to v8.0

If you are 100% sure prev version was v7 (not v6), probably your v7 font was generated without kerning. But i strongly NOT recommend to use such kludges. It would be better to make small rework, as said im my prev post.

**Comment by david-res** [comment]
@embeddedt I may be very wrong about the versions. I mentioned it because I recall reading a thread not too long ago where it was mentioned. It might have been in regards to the image converter now that I think of it, or just an old thread that was bumped.
@puzrin what would cause the difference if the same font file was used to generate the custom LV fonts?

**Comment by puzrin** [comment]
@david-res 

> what would cause the difference if the same font file was used to generate the custom LV fonts?

If the same convertor + the same vector font (TTF) => probably you missed kerning in previous run (not checked appropriate checkbox). Note, possibility to exclude kerning info is very tricky and not expected to be used wide.

https://en.wikipedia.org/wiki/Kerning.

Also, with proportional (not monospaced) font, even lack of kerning should not exclude drift when digits changed ("111" can be more narrow than "999", for example)
