### ISSUE TITLE
Can use lv_font_conv as node.js module ?

### ISSUE THREAD

**Issue by maxpromer** [lvgl/lv_font_conv#78]
My project use Node.js (JavaScript) and i needs use lv_font_conv but i not found how i can add lv_font_conv to my project with use as module so are you have some sample code use it as module ?

**Comment by puzrin** [comment]
There was no goal to privide library API, but you can do `require('lv_font_conv/lib/convert')` and inspect the code, how it's used, about options. Or just call CLI script via `.execSync()`
