### ISSUE TITLE
Can't convert font 

### ISSUE THREAD

**Issue by sbltlh** [lvgl/lv_font_conv#79]
I am trying to extract the block characters (https://unicode-table.com/en/blocks/block-elements/) from the GPL DroidSansMono.ttf. I can inspect the font file with Character Map on my Linux box and see that the symbols are there in the font file, but the online and offline tools both fail to convert them using range or pasted symbols.

**Comment by puzrin** [comment]
You did not provided any info how to reproduce. Also, for usage questions forum is preferred.

**Comment by sbltlh** [comment]
1. Download droidsansmono.zip from https://www.typewolf.com/droid-sans-mono
2. In the online font converter:
- Give it a name
- Select the extracted font
- Size 14
- 1bpp
- Use these three symbols: ▄█▀

This isn't a usage question.

**Comment by sbltlh** [comment]
BTW, this also fails using the fontawesome font that is linked on the page.

**Comment by embeddedt** [comment]
@sbltlh According to FontForge, this font does not have at least one of those symbols (the first one). Note the X underneath the glyph label.

![image](https://user-images.githubusercontent.com/42941056/172382552-6a46a9d5-6228-4ecc-baae-2e3d7303a554.png)
