### ISSUE TITLE
Add fallback cli option

### ISSUE THREAD

**Issue by kutu** [lvgl/lv_font_conv#87]
Currently `const lv_font_t my_font` is const, and `fallback` field can only be assigned by editing `my_font.c` directly.

after this line
https://github.com/lvgl/lv_font_conv/blob/49559663c82cf88939b10b67de028569852b0a1f/lib/writers/lvgl/lv_table_head.js#L77
add
```c
.fallback = &lv_font_montserrat_12,
```
where `lv_font_montserrat_12` will be `fallback` cli option

**Comment by kisvegabor** [comment]
It's really useful. @puzrin?

**Comment by puzrin** [comment]
I dont' track current state of lvgl. Is `.fallback` something specific to new version?

**Comment by kutu** [comment]
https://docs.lvgl.io/8.3/overview/font.html#use-font-fallback
I started with lvgl8.3, so I don't know how old this option is

if I try to assign fallback option like in docs
```c
my_font.fallback = &lv_font_montserrat_12;
```
I got error
```
Cannot assign to variable 'my_font' with const-qualified type 'const lv_font_t' (aka 'const struct _lv_font_t') ​clang(typecheck_assign_const)
```

**Comment by kisvegabor** [comment]
It was [added in v8.2](https://docs.lvgl.io/8.3/CHANGELOG.html#v8-2-0-31-january-2022).
