### ISSUE TITLE
No release for over 2 years.

### ISSUE THREAD

**Issue by hummel-32** [lvgl/lv_font_conv#95]
Hi,

I have recently updated my lvgl tools and it occurred to me that lv_font_conv hasn't seen any releases for the last two years. Is there a reason why releases have stopped? Are you waiting to complete some milestone before doing the next release?

I think the changes since the last release come in very handy and it would be great if I could just install the package via npm ;)

@puzrin 

Best regards,
Hummel

**Comment by FederAndInk** [comment]
up, a release would be greatly appreciated :+1:

**Comment by puzrin** [comment]
Sorry, switched to another projects. As far as I remember, I granted you full admin permissions in npm registry, to avoid any dependencies on me.

Also, users can run any commit via `npx` https://github.com/lvgl/lv_font_conv?tab=readme-ov-file#install-the-script without waiting for release.

**Comment by puzrin** [comment]
AFAIK, core and binary format are stable for a long time. As soon as LVGL could support binary format instead of custom text one, there will be no need to change anything here.

**Comment by kisvegabor** [comment]
Alright, thank you. I just wanted to be sure about your intentions. 

I've checked that my NPX account is still working and I see both packages:
![image](https://github.com/lvgl/lv_font_conv/assets/7599318/bebfbe13-84dd-499d-abc2-a034607c1a0d)

However, in lack of free time I cannot take the maintenance of this repo either. If you tell me how to create a new release for the package, I can do that, but I cannot contribute with creative and responsible ideas. :slightly_frowning_face:

**Comment by puzrin** [comment]
I usually do something like this:

- `git clone ...`
- `npm i`
- Make sure changelog is consistent, update if required
- Update `pachage.json` with new version
- Do commit `x.y.z. released` and add git tag
- `git push`
- `npm publish`
- `git push --tags`



> but I cannot contribute with creative and responsible ideas. 🙁

IMHO good project should be stable without creative ideas :). Take a look at the commits history. IMHO those are related to lvgl text format and web only. Core bugs were closed more than 2 years ago.

**Comment by kisvegabor** [comment]
Thanks! I've just updated `package.json` to `v1.5.3`. Please test it, and if it looks good I'll tag and release it.

**Comment by AvaGhafari** [comment]
@kisvegabor we've tested the last commit, everything works fine with LVGL 9. We would really appreciate if you tag the repo.
Thanks.

**Comment by kisvegabor** [comment]
I've tried `npm publish` but got an error:
```
npm publish

> lv_font_conv@1.5.3 prepublishOnly
> npm run shrink-deps


> lv_font_conv@1.5.3 shrink-deps
> shx rm -rf node_modules/opentype.js/src node_modules/opentype.js/dist/opentype.{m,js.m}* node_modules/pngjs/browser.js

sh: 1: shx: not found
npm error code 127
npm error path /home/kisvegabor/projects/lvgl/lv_font_conv
npm error command failed
npm error command sh -c npm run shrink-deps
npm error A complete log of this run can be found in: /home/kisvegabor/.npm/_logs/2024-06-04T13_07_39_773Z-debug-0.log
```
```
kisvegabor ~/projects/lvgl/lv_font_conv $ (master) cat /home/kisvegabor/.npm/_logs/2024-06-04T13_07_39_773Z-debug-0.log
0 verbose cli /home/kisvegabor/.nvm/versions/node/v20.11.1/bin/node /home/kisvegabor/.nvm/versions/node/v20.11.1/bin/npm
1 info using npm@10.8.1
2 info using node@v20.11.1
3 silly config load:file:/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/npmrc
4 silly config load:file:/home/kisvegabor/projects/lvgl/lv_font_conv/.npmrc
5 silly config load:file:/home/kisvegabor/.npmrc
6 silly config load:file:/home/kisvegabor/.nvm/versions/node/v20.11.1/etc/npmrc
7 verbose title npm publish
8 verbose argv "publish"
9 verbose logfile logs-max:10 dir:/home/kisvegabor/.npm/_logs/2024-06-04T13_07_39_773Z-
10 verbose logfile /home/kisvegabor/.npm/_logs/2024-06-04T13_07_39_773Z-debug-0.log
11 verbose publish [ '.' ]
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 verbose stack Error: command failed
14 verbose stack     at promiseSpawn (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
14 verbose stack     at spawnWithShell (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
14 verbose stack     at promiseSpawn (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
14 verbose stack     at runScriptPkg (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
14 verbose stack     at runScript (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
14 verbose stack     at #publish (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/commands/publish.js:88:13)
14 verbose stack     at async Publish.exec (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/commands/publish.js:46:5)
14 verbose stack     at async Npm.exec (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/npm.js:207:9)
14 verbose stack     at async module.exports (/home/kisvegabor/.nvm/versions/node/v20.11.1/lib/node_modules/npm/lib/cli/entry.js:74:5)
15 verbose pkgid lv_font_conv@1.5.3
16 error code 127
17 error path /home/kisvegabor/projects/lvgl/lv_font_conv
18 error command failed
19 error command sh -c npm run shrink-deps
20 verbose cwd /home/kisvegabor/projects/lvgl/lv_font_conv
21 verbose os Linux 5.15.0-101-generic
22 verbose node v20.11.1
23 verbose npm  v10.8.1
24 verbose exit 127
25 verbose code 127
26 error A complete log of this run can be found in: /home/kisvegabor/.npm/_logs/2024-06-04T13_07_39_773Z-debug-0.log
```

**Comment by xperiments** [comment]
@kisvegabor I think what is missing is to install shx dependency, not sure is local or global

npm install shx 
or
npm install shx -g

Can y try?

**Comment by kisvegabor** [comment]
It worked, thank you! 

![image](https://github.com/lvgl/lv_font_conv/assets/7599318/ae74b87c-2dfb-457e-aa7a-eff0a2bd1616)

**Comment by kisvegabor** [comment]
Closing this issue. Thank you for the support!

**Comment by puzrin** [comment]
Seems changelog update missed.

**Comment by kisvegabor** [comment]
True, can anyone send a PR?
