### ISSUE TITLE
I use "Online font converter" and "SquareLine" to gen font but the the compress not work!!! 

### ISSUE THREAD

**Issue by Staok** [lvgl/lv_font_conv#98]
In "Online font converter" I checked the checkBox of "Enable Font compression" but no significant reduction in size of the output fons .c file, same thing happened in SquareLine(by not add "--no-compress" to the "Custom" option box)

why???

![image](https://github.com/lvgl/lv_font_conv/assets/59993573/e8595f36-19c1-4f61-bbe7-bd13dfd9b2c8)

this pic show the "use compress" output the "ui_font_fontRef36Compress.c", and "not use compress" output is "ui_font_fontReg36.c", they are the same size, why???

**Comment by kisvegabor** [comment]
I've tested with the online font converter using these settings
![image](https://github.com/lvgl/lv_font_conv/assets/7599318/a8f6b35b-efcb-44db-8faf-a8dce81f984d)


And it works for me:
[fonts.zip](https://github.com/lvgl/lv_font_conv/files/14081478/fonts.zip)


Can you try to reproduce it?

**Comment by Staok** [comment]
@kisvegabor 
I see your test screenshot is use 4bpp, I tried with that and it compressed well
In the first time I using the 1bpp, so the compress function not work well with 1bpp??
